### ISSUE TITLE
Mark external links

### ISSUE THREAD

**Issue by Ryuno-Ki** [KirstieJane/STEMMRoleModels#59]
Since internal links are written relatively, it is easy to insert an icon (like ![](https://en.wikipedia.org/w/skins/Vector/images/external-link-ltr-icon.png?325de)) for all links with href [starting](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors#Summary) with `http`. I think, it would help navigating the site.

Something along this:

``` css
a[href^="http"]::after {
    content: " ";
    display: inline-block;
    background-mage: url('https://en.wikipedia.org/w/skins/Vector/images/external-link-ltr-icon.png');
    height: 12px;
    width: 12px;
    margin-left: 0.5em;
}
```
