### ISSUE TITLE
Rescale pictures so they aren't so large

### ISSUE THREAD

**Issue by KirstieJane** [KirstieJane/STEMMRoleModels#98]
At the moment our lovely search_database code can re-size the role models' pictures for the [main page](http://stemmrolemodels.com/site/search_database) but not when individual role models are clicked for a more detailed view.

I've tried in vain to change the width of the picture on line but it doesn't seem to work!

Here's the part of [stylesheets/style.less](https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/stylesheets/style.less#L180) that contains the css to format the main page.

Here's the part of [stylesheets/style.less](https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/stylesheets/style.less#L491) that _I think_ contains the css to format the picture on the detailed pop up (But I can't seem to change the appearance so I might be wrong!)

Here's the part of [js/app.js](https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/js/app.js#L205) that mentions the `speaker-photo` we want to show.

Any suggestions on how to resize the picture so it's a fixed width on the detailed card would be super helpful!

**Comment by KirstieJane** [comment]
Hi @auremoser and @acabunoc - this is where I'm stuck now if you have any time today to fork the repo and see why I can't change the pictures! THANK YOU!

**Comment by KirstieJane** [comment]
Hi @geminiimatt and @bmpvieira - thank you for starring the repo!

If either of you have any time too look at this issue I'd LOVE to know the answer - it's been driving me crazy all morning 😄

**Comment by abbycabs** [comment]
You can probably use max-width to scale
https://developer.mozilla.org/en/docs/Web/CSS/max-width

**Comment by abbycabs** [comment]
![screen shot 2016-10-12 at 11 13 48](https://cloud.githubusercontent.com/assets/617994/19315853/57fcba2e-906d-11e6-900d-0de5350e2ec9.png)

You can add max-width:100% to the image. I can send over a PR later if you need it!

**Comment by Ryuno-Ki** [comment]
Either of those snippets will work on the img:

``` css
img.scale-width {
  display: block; /* needed for styling height & width */
  max-height: 100%; /* don't expand over parent container */
  width: auto; /* keep aspect ratio */
}
```

or

``` css
img.scale-height {
  display: block; /* needed for styling height & width */
  height: auto; /* keep aspect ratio */
  max-width: 100%; /* don't expand over parent container */
}
```

Just add `scale-height` or `scale-width` to the `<img>` tag in HTML then. Text between `/*` and `*/` are CSS comments and will be ignored by the web browser. I've added explanation for the rules in there. You may want to omit them in production to reduce file size and hence save bandwidth.
